In [171]:
# Tayyip GÜNEY 05.06.2022
# NumPy Exercises

import numpy as np

In [172]:
# 1) Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.

# Vektorler tek boyutlu, matrisler cok boyutlu listelerdir.

In [173]:
# 2) 10 elemanli bir listeden NumPy Array’i olusturunuz.

a1 = [1,2,3,4,5,6,7,8,9,10]

a2 = np.array(a1)
a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [174]:
# 3) Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.

zero = np.zeros((10,10),dtype="int")
zero

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [175]:
# 4) Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.
one = np.ones((10,10),dtype="float")
one

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [176]:
# 5) Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.

nine = np.full((10,10),9,dtype="int")
nine

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [177]:
# 6) 5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.

q6 = np.arange(5,25,3)
q6

array([ 5,  8, 11, 14, 17, 20, 23])

In [178]:
# 7) -1 ile 1 arasinda 30 adet Array olusturunuz.

q7 = np.linspace(-1,1,30)
q7

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

In [179]:
# 8) 0 ile 30 arasinda 5x6’lik bir matris olusturun.

q8 = np.random.randint(0,30,(5,6))
q8

array([[10, 19, 19, 24,  3, 13],
       [ 3,  1,  6,  7,  3, 28],
       [ 8,  3, 24,  6, 22, 13],
       [22,  8,  4,  2,  1, 18],
       [17, 14, 22, 14,  9, 18]])

In [180]:
# 9) Kosegenleri 1 olan 10x10’luk bir matris olusturunuz.

q9 = np.eye(10,10)
q9

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [181]:
# 10) 0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin; 
# • eleman sayisini • boyut bilgisini/sayisini • satir X sutun bilgisini • veri tipini numpy metodlariyla yazdiriniz.

q10 = np.random.randint(0,10,(5,10))
print("Matris : ",q10)
print("eleman sayisi         : ",q10.size)
print("boyut bilgisi         : ",q10.ndim)
print("satir X sutun bilgisi : ",q10.shape)
print("veri tipi             : ",q10.dtype)


Matris :  [[3 2 6 9 4 5 1 7 9 7]
 [8 0 1 9 9 0 9 0 9 8]
 [6 2 0 8 1 4 8 9 6 7]
 [6 7 8 6 4 0 3 1 7 5]
 [1 7 9 7 8 2 3 0 4 6]]
eleman sayisi         :  50
boyut bilgisi         :  2
satir X sutun bilgisi :  (5, 10)
veri tipi             :  int32


In [182]:
# 11) 0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. (3 boyutlu bir matris olusturulacak)

q11 = np.random.randint(0,10,(3,4,7))
q11

array([[[3, 3, 6, 0, 1, 4, 8],
        [1, 5, 9, 9, 3, 9, 3],
        [1, 6, 9, 8, 9, 3, 1],
        [7, 7, 0, 8, 9, 4, 9]],

       [[1, 4, 9, 4, 7, 4, 9],
        [4, 5, 8, 6, 1, 7, 3],
        [6, 0, 0, 9, 7, 2, 5],
        [3, 9, 9, 1, 3, 3, 2]],

       [[8, 5, 7, 4, 1, 8, 2],
        [1, 5, 9, 5, 2, 0, 6],
        [1, 7, 7, 8, 6, 3, 2],
        [5, 2, 3, 3, 9, 9, 4]]])

In [183]:
# 12) Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)

q12 = np.arange(1,7)
print("vektor : ",q12)
q12_ = q12.reshape((3,2))
print("matris : ",q12_)

vektor :  [1 2 3 4 5 6]
matris :  [[1 2]
 [3 4]
 [5 6]]


In [184]:
# 13) 4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.

a13 = np.arange(1,6)
b13 = np.arange(6,11)
c13 = np.arange(11,16)
d13 = np.arange(16,21)

np.concatenate([a13,c13,d13,b13])

array([ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,  6,  7,
        8,  9, 10])

In [185]:
# 14) 2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz,

a14 = np.random.randint(0,10,(5,2))

b14 = np.random.randint(21,26,(5,2))

c14 = np.concatenate((a14,b14),axis=1)


print("vektor   : ",a14)
print("\nmatris   : ",b14)
print("\nBirlesim : ",c14)

vektor   :  [[9 5]
 [8 7]
 [1 4]
 [1 7]
 [5 4]]

matris   :  [[23 24]
 [25 24]
 [21 25]
 [23 23]
 [25 22]]

Birlesim :  [[ 9  5 23 24]
 [ 8  7 25 24]
 [ 1  4 21 25]
 [ 1  7 23 23]
 [ 5  4 25 22]]


In [186]:
# 15) Numpy’da “axis=1” ve “axis=0” arasinda ne fark vardir. Teorik olarak yaziniz?

# axis = 0 satırlar icin (y eksenini) 
# axis = 1 sütunlar için (x eksenini)

In [187]:
# 16) Farkli boyutlardaki arraylari satin ve sutun bazli ayri ayri birlestiriniz.

a15 = np.random.randint(0,10,(5,2))

b15 = np.random.randint(21,26,(5,2))

c15 = np.concatenate((a14,b14),axis=1)
d15 = np.concatenate((a14,b14),axis=0)


print("vektor   : ",a15)
print("\nmatris   : ",b15)
print("\nBirlesim(Sutun) : ",c15)
print("\nBirlesim(Satir) : ",d15)


vektor   :  [[4 1]
 [4 4]
 [3 8]
 [4 5]
 [3 9]]

matris   :  [[25 21]
 [23 25]
 [24 24]
 [25 21]
 [25 21]]

Birlesim(Sutun) :  [[ 9  5 23 24]
 [ 8  7 25 24]
 [ 1  4 21 25]
 [ 1  7 23 23]
 [ 5  4 25 22]]

Birlesim(Satir) :  [[ 9  5]
 [ 8  7]
 [ 1  4]
 [ 1  7]
 [ 5  4]
 [23 24]
 [25 24]
 [21 25]
 [23 23]
 [25 22]]


In [188]:
# 17) 10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 5 ayri array olusturunuz.

a17 = np.arange(10)
c,v,b,n,m = np.split(a17,5)
print(c)
print(v)
print(b)
print(n)
print(m)



[0 1]
[2 3]
[4 5]
[6 7]
[8 9]


In [189]:
# 18) Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz.
# Ve bu siralamadan sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.

a18 = np.random.randint(1,11,10)
print("Array  : ", a18)
a18.sort()
# print("Sorted : ", sorted(a18))
print("Sorted : ", a18)

for i,v in enumerate(a18):
    print(f"index {i} = {v}")


Array  :  [9 3 1 6 2 4 1 7 2 1]
Sorted :  [1 1 1 2 2 3 4 6 7 9]
index 0 = 1
index 1 = 1
index 2 = 1
index 3 = 2
index 4 = 2
index 5 = 3
index 6 = 4
index 7 = 6
index 8 = 7
index 9 = 9


In [190]:
# 19) 20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.

a19 = np.random.randint(1,21,20)
index = [2,4,6]
print(a19)
print(50*"*")
print(a19[index])


[11 11 19  8  1 17  5 11 14  9 12 17 17 10  4  2  8 10 18  6]
**************************************************
[19  1  5]


In [191]:
# 20) 10 elemanli random bir vektor olusturunuz ve bu arrayin 4. elemanini farkli bir sayiyla degistiriniz.

a20 = np.random.randint(10,99,10)
print(a20)
a20[3]=4408
print(a20)

[29 73 70 41 45 26 45 49 97 85]
[  29   73   70 4408   45   26   45   49   97   85]


In [192]:
# 21) “Diagonal Matrix” ve “Trace of Matrix” kavramlari hakkinda kucuk bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.

# Diagonal Matrix : Bir matriste köşegen dışı tüm girişlerin sıfır olduğu bir matristir.

# Trace of Matrix : Bir kare matrisin izi, köşegen girişlerinin toplamıdır.

In [193]:
# 22) 5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)

a_diag = np.diag(np.random.randint(1,10,5))
print(a_diag)

for i in range(len(a_diag)):
    print(f"a_diag[{i},{i}] : {a_diag[i,i]}")

[[3 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 9 0]
 [0 0 0 0 3]]
a_diag[0,0] : 3
a_diag[1,1] : 3
a_diag[2,2] : 2
a_diag[3,3] : 9
a_diag[4,4] : 3


In [194]:
# 23) 10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.

a23 = np.arange(10,20)
print(a23)
print(50*"*")
print(a23[3:])

[10 11 12 13 14 15 16 17 18 19]
**************************************************
[13 14 15 16 17 18 19]


In [195]:
# 24) 10X10 luk bir matris olusturunuz ve ; 

# 24a - 3.satir ve 5.sutuna ulasiniz. 
# 24b - 5.sutunun tum satirlarina ulasiniz. 
# 24c - Tum sutunlarin 2.satirlarina ulasiniz. 
# 24d - tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz. 
# 24e - satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz. 
# 24f - satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz. 
# 24g - sutun indexi sadece 3, 6, 9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz. 
# 24h - 5.indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz.

# NOT : elemanlara ulasirken; eleman-1 = index olarak alinmistir (2.eleman = 1.index)

a24 = np.random.randint(10,99,(10,10))
print("Matris : \n", a24)
print(50*"*")
print("24a : \n", a24[2,4])           # 24a - 3.satir ve 5.sutuna ulasiniz. 
print("24b : \n", a24[4,:])           # 24b - 5.sutunun tum satirlarina ulasiniz. 
print("24c : \n", a24[1,:])           # 24c - Tum sutunlarin 2.satirlarina ulasiniz. 
print("24d : \n", a24[1:7,:])         # 24d - tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz. 


Matris : 
 [[28 91 94 19 81 64 42 21 78 70]
 [32 79 41 73 29 57 48 53 47 45]
 [18 41 55 39 20 15 63 23 64 61]
 [46 43 58 15 80 90 18 94 46 15]
 [43 71 72 66 98 77 12 14 58 42]
 [14 22 61 28 80 11 90 64 62 88]
 [91 43 91 58 29 62 77 32 96 54]
 [57 24 22 42 77 83 20 33 37 19]
 [82 82 32 77 37 30 10 27 36 39]
 [13 87 26 67 76 80 34 51 45 69]]
**************************************************
24a : 
 20
24b : 
 [43 71 72 66 98 77 12 14 58 42]
24c : 
 [32 79 41 73 29 57 48 53 47 45]
24d : 
 [[32 79 41 73 29 57 48 53 47 45]
 [18 41 55 39 20 15 63 23 64 61]
 [46 43 58 15 80 90 18 94 46 15]
 [43 71 72 66 98 77 12 14 58 42]
 [14 22 61 28 80 11 90 64 62 88]
 [91 43 91 58 29 62 77 32 96 54]]


In [196]:
# 24) devami.................

print("Matris : \n", a24)
print(50*"*")
print("24e : \n", a24[2:6,3:8])       # 24e - satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz. 
print("24f : \n", a24[5:,:5])         # 24f - satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz.  

Matris : 
 [[28 91 94 19 81 64 42 21 78 70]
 [32 79 41 73 29 57 48 53 47 45]
 [18 41 55 39 20 15 63 23 64 61]
 [46 43 58 15 80 90 18 94 46 15]
 [43 71 72 66 98 77 12 14 58 42]
 [14 22 61 28 80 11 90 64 62 88]
 [91 43 91 58 29 62 77 32 96 54]
 [57 24 22 42 77 83 20 33 37 19]
 [82 82 32 77 37 30 10 27 36 39]
 [13 87 26 67 76 80 34 51 45 69]]
**************************************************
24e : 
 [[39 20 15 63 23]
 [15 80 90 18 94]
 [66 98 77 12 14]
 [28 80 11 90 64]]
24f : 
 [[14 22 61 28 80]
 [91 43 91 58 29]
 [57 24 22 42 77]
 [82 82 32 77 37]
 [13 87 26 67 76]]


In [197]:
# 24) devami.................

print("Matris : \n", a24)
print(50*"*")
print("24g : \n", a24[:,(3,6,9)])         # 24g - sutun indexi sadece 3, 6, 9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz. 
a24[5,5]=1995
print("24h : \n", a24[5,5])             # 24h - 5.indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz.


Matris : 
 [[28 91 94 19 81 64 42 21 78 70]
 [32 79 41 73 29 57 48 53 47 45]
 [18 41 55 39 20 15 63 23 64 61]
 [46 43 58 15 80 90 18 94 46 15]
 [43 71 72 66 98 77 12 14 58 42]
 [14 22 61 28 80 11 90 64 62 88]
 [91 43 91 58 29 62 77 32 96 54]
 [57 24 22 42 77 83 20 33 37 19]
 [82 82 32 77 37 30 10 27 36 39]
 [13 87 26 67 76 80 34 51 45 69]]
**************************************************
24g : 
 [[19 42 70]
 [73 48 45]
 [39 63 61]
 [15 18 15]
 [66 12 42]
 [28 90 88]
 [58 77 54]
 [42 20 19]
 [77 10 39]
 [67 34 69]]
24h : 
 1995


In [198]:
# 25) 0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin;

# 25a - 20 den buyuk olan kac deger var.
# 25b - 30’dan kucuk kac deger var 
# 25c - icerisinde 33 gecen kac deger var
# 25d - olusturulan arrayin tum elemanlarini 5 ile carpin.
# 25e - olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.

a25 = np.arange(0,51,5)
print("Array : \n", a25)

print("25a : \n", (a25[a25>20]).size)
print("25b : \n", (a25[a25<30]).size)
print("25c : \n", (a25[a25==33]).size)
print("25d : \n", (a25*5))
print("25e : \n", a25%2)



Array : 
 [ 0  5 10 15 20 25 30 35 40 45 50]
25a : 
 6
25b : 
 6
25c : 
 0
25d : 
 [  0  25  50  75 100 125 150 175 200 225 250]
25e : 
 [0 1 0 1 0 1 0 1 0 1 0]


In [199]:
# 26) 0 ile 1 arasinda 50 elamanli bir array olusturunuz ve;

# 26a - orlamasini aliniz.
# 26b - standart sapmasini aliniz. 
# 26c - varyansini aliniz.
# 26d - median’ini aliniz.
# 26e - en kucuk degeri bulunuz.
# 26f - en buyuk degeri bulunuz. 

a26 = np.linspace(0,1,50)
print("Array : \n", a26)
print("26a : \n", a26.sum()/a26.size)
print("26b : \n", a26.std())
print("26c : \n", a26.var())
print("26d : \n", np.median(a26))
print("26e : \n", np.min(a26))
print("26e : \n", np.max(a26))


Array : 
 [0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]
26a : 
 0.5
26b : 
 0.2945075446869757
26c : 
 0.086734693877551
26d : 
 0.5
26e : 
 0.0
26e : 
 1.0


# Master odev  
Bir dongu icerisinde random olacak sekilde iki tane 20x20’luk matris uretin ve bu matrislerin farklarini alin. 
Ve fark matrisinin diagonali, -0.1 ile 0.1 arasinda olana kadar bu islemi tekrarlayin. 
Istenilen matris bulundugunda program dursun ve toplam kac dongunun kuruldugunu,
ne kadar sure icinde buldugunu ve istenilen matrisi print ile birlikte ekrana yazdiriniz... 
Tavsiye: 20 x 20 luk matrisin bulunmasi saatler surebilir. Bu yuzden algoritmanizin dogrulugunu test etmek icin once 4x4, 
5x5 gibi kucuk matrislerde deneyebilirsiniz. Ve matris sayisisini arttirarak en son 20x20 u deneyebilirsiniz.


In [ ]:
from datetime import datetime
import numpy as np

ts = datetime.now()     # start time
n=0                     # number of iterations
matrix_len=20           # matrix length 

while True:
    n+=1                
    check = True        # control for while loop
    
    mtx1 = np.random.rand(matrix_len,matrix_len)
    mtx2 = np.random.rand(matrix_len,matrix_len)
    diag_m = np.diag(mtx1-mtx2)
    
    for i in diag_m:
        if i<-0.1 or i > 0.1: # check=false if any value is not in the requested range
            check = False
            break
    
    if check == True:        # If check = true, after the for loop, the process is complete
        print("Diagonal Matrix :\n",diag_m)
        print(50*"*")
        break

te = datetime.now()     # end time
process_time = (te-ts)

print("\nnumber of iterations      : ", n)
print("\ntotal processing time(s)  : ", process_time)
